<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| Технически данни за пистите
|--------------------------------------------------------------------------
|
| Публични факти (Wikipedia) за активните писти от календара. Ключът е
| jolpica_id (както е в races.jolpica_id). Полета с null означават, че данните
| не са сигурни/налични — UI ги скрива грациозно.
|
| type: 'street' | 'permanent' | 'hybrid'
| surface_grip / overtaking_difficulty: 'low' | 'medium' | 'high'
| lap_record_* може да е null, ако официалният рекорд не е сигурен.
|
*/

return [
    'monaco' => ['length_km' => 3.337, 'laps' => 78, 'turns_count' => 19, 'fast_corners' => 3, 'medium_corners' => 6, 'slow_corners' => 10, 'straights_count' => 2, 'longest_straight_m' => 600, 'lap_record_time' => '1:12.909', 'lap_record_driver' => 'Lewis Hamilton', 'lap_record_year' => 2021, 'elevation_change_m' => 42, 'type' => 'street', 'surface_grip' => 'low', 'overtaking_difficulty' => 'high'],
    'silverstone' => ['length_km' => 5.891, 'laps' => 52, 'turns_count' => 18, 'fast_corners' => 9, 'medium_corners' => 5, 'slow_corners' => 4, 'straights_count' => 3, 'longest_straight_m' => 770, 'lap_record_time' => '1:27.097', 'lap_record_driver' => 'Max Verstappen', 'lap_record_year' => 2020, 'elevation_change_m' => 13, 'type' => 'permanent', 'surface_grip' => 'high', 'overtaking_difficulty' => 'medium'],
    'spa' => ['length_km' => 7.004, 'laps' => 44, 'turns_count' => 19, 'fast_corners' => 10, 'medium_corners' => 5, 'slow_corners' => 4, 'straights_count' => 3, 'longest_straight_m' => 1900, 'lap_record_time' => '1:46.286', 'lap_record_driver' => 'Valtteri Bottas', 'lap_record_year' => 2018, 'elevation_change_m' => 102, 'type' => 'permanent', 'surface_grip' => 'high', 'overtaking_difficulty' => 'medium'],
    'monza' => ['length_km' => 5.793, 'laps' => 53, 'turns_count' => 11, 'fast_corners' => 5, 'medium_corners' => 2, 'slow_corners' => 4, 'straights_count' => 4, 'longest_straight_m' => 1130, 'lap_record_time' => '1:21.046', 'lap_record_driver' => 'Rubens Barrichello', 'lap_record_year' => 2004, 'elevation_change_m' => 12, 'type' => 'permanent', 'surface_grip' => 'medium', 'overtaking_difficulty' => 'low'],
    'suzuka' => ['length_km' => 5.807, 'laps' => 53, 'turns_count' => 18, 'fast_corners' => 8, 'medium_corners' => 6, 'slow_corners' => 4, 'straights_count' => 2, 'longest_straight_m' => 1200, 'lap_record_time' => '1:30.983', 'lap_record_driver' => 'Lewis Hamilton', 'lap_record_year' => 2019, 'elevation_change_m' => 40, 'type' => 'permanent', 'surface_grip' => 'high', 'overtaking_difficulty' => 'medium'],
    'albert_park' => ['length_km' => 5.278, 'laps' => 58, 'turns_count' => 14, 'fast_corners' => 6, 'medium_corners' => 4, 'slow_corners' => 4, 'straights_count' => 4, 'longest_straight_m' => 900, 'lap_record_time' => '1:19.813', 'lap_record_driver' => 'Charles Leclerc', 'lap_record_year' => 2024, 'elevation_change_m' => 6, 'type' => 'hybrid', 'surface_grip' => 'medium', 'overtaking_difficulty' => 'medium'],
    'bahrain' => ['length_km' => 5.412, 'laps' => 57, 'turns_count' => 15, 'fast_corners' => 5, 'medium_corners' => 4, 'slow_corners' => 6, 'straights_count' => 3, 'longest_straight_m' => 1090, 'lap_record_time' => '1:31.447', 'lap_record_driver' => 'Pedro de la Rosa', 'lap_record_year' => 2005, 'elevation_change_m' => 18, 'type' => 'permanent', 'surface_grip' => 'medium', 'overtaking_difficulty' => 'high'],
    'jeddah' => ['length_km' => 6.174, 'laps' => 50, 'turns_count' => 27, 'fast_corners' => 15, 'medium_corners' => 8, 'slow_corners' => 4, 'straights_count' => 3, 'longest_straight_m' => 1100, 'lap_record_time' => '1:30.734', 'lap_record_driver' => 'Lewis Hamilton', 'lap_record_year' => 2021, 'elevation_change_m' => 5, 'type' => 'street', 'surface_grip' => 'high', 'overtaking_difficulty' => 'medium'],
    'imola' => ['length_km' => 4.909, 'laps' => 63, 'turns_count' => 19, 'fast_corners' => 7, 'medium_corners' => 5, 'slow_corners' => 7, 'straights_count' => 2, 'longest_straight_m' => 650, 'lap_record_time' => '1:15.484', 'lap_record_driver' => 'Lewis Hamilton', 'lap_record_year' => 2020, 'elevation_change_m' => 30, 'type' => 'permanent', 'surface_grip' => 'medium', 'overtaking_difficulty' => 'high'],
    'miami' => ['length_km' => 5.412, 'laps' => 57, 'turns_count' => 19, 'fast_corners' => 8, 'medium_corners' => 5, 'slow_corners' => 6, 'straights_count' => 3, 'longest_straight_m' => 1280, 'lap_record_time' => '1:29.708', 'lap_record_driver' => 'Max Verstappen', 'lap_record_year' => 2023, 'elevation_change_m' => 3, 'type' => 'street', 'surface_grip' => 'medium', 'overtaking_difficulty' => 'medium'],
    'catalunya' => ['length_km' => 4.657, 'laps' => 66, 'turns_count' => 14, 'fast_corners' => 6, 'medium_corners' => 4, 'slow_corners' => 4, 'straights_count' => 2, 'longest_straight_m' => 1047, 'lap_record_time' => null, 'lap_record_driver' => null, 'lap_record_year' => null, 'elevation_change_m' => 30, 'type' => 'permanent', 'surface_grip' => 'high', 'overtaking_difficulty' => 'medium'],
    'red_bull_ring' => ['length_km' => 4.318, 'laps' => 71, 'turns_count' => 10, 'fast_corners' => 5, 'medium_corners' => 2, 'slow_corners' => 3, 'straights_count' => 3, 'longest_straight_m' => 626, 'lap_record_time' => '1:05.619', 'lap_record_driver' => 'Carlos Sainz', 'lap_record_year' => 2020, 'elevation_change_m' => 65, 'type' => 'permanent', 'surface_grip' => 'medium', 'overtaking_difficulty' => 'high'],
    'hungaroring' => ['length_km' => 4.381, 'laps' => 70, 'turns_count' => 14, 'fast_corners' => 4, 'medium_corners' => 6, 'slow_corners' => 4, 'straights_count' => 1, 'longest_straight_m' => 700, 'lap_record_time' => '1:16.627', 'lap_record_driver' => 'Lewis Hamilton', 'lap_record_year' => 2020, 'elevation_change_m' => 35, 'type' => 'permanent', 'surface_grip' => 'low', 'overtaking_difficulty' => 'high'],
    'zandvoort' => ['length_km' => 4.259, 'laps' => 72, 'turns_count' => 14, 'fast_corners' => 7, 'medium_corners' => 3, 'slow_corners' => 4, 'straights_count' => 2, 'longest_straight_m' => 640, 'lap_record_time' => '1:11.097', 'lap_record_driver' => 'Lewis Hamilton', 'lap_record_year' => 2021, 'elevation_change_m' => 18, 'type' => 'permanent', 'surface_grip' => 'high', 'overtaking_difficulty' => 'high'],
    'marina_bay' => ['length_km' => 4.940, 'laps' => 62, 'turns_count' => 19, 'fast_corners' => 6, 'medium_corners' => 6, 'slow_corners' => 7, 'straights_count' => 3, 'longest_straight_m' => 832, 'lap_record_time' => null, 'lap_record_driver' => null, 'lap_record_year' => null, 'elevation_change_m' => 5, 'type' => 'street', 'surface_grip' => 'medium', 'overtaking_difficulty' => 'high'],
    'americas' => ['length_km' => 5.513, 'laps' => 56, 'turns_count' => 20, 'fast_corners' => 9, 'medium_corners' => 6, 'slow_corners' => 5, 'straights_count' => 2, 'longest_straight_m' => 1015, 'lap_record_time' => '1:36.169', 'lap_record_driver' => 'Charles Leclerc', 'lap_record_year' => 2019, 'elevation_change_m' => 41, 'type' => 'permanent', 'surface_grip' => 'medium', 'overtaking_difficulty' => 'medium'],
    'rodriguez' => ['length_km' => 4.304, 'laps' => 71, 'turns_count' => 17, 'fast_corners' => 6, 'medium_corners' => 5, 'slow_corners' => 6, 'straights_count' => 2, 'longest_straight_m' => 1200, 'lap_record_time' => '1:17.774', 'lap_record_driver' => 'Valtteri Bottas', 'lap_record_year' => 2021, 'elevation_change_m' => 10, 'type' => 'permanent', 'surface_grip' => 'low', 'overtaking_difficulty' => 'medium'],
    'interlagos' => ['length_km' => 4.309, 'laps' => 71, 'turns_count' => 15, 'fast_corners' => 6, 'medium_corners' => 4, 'slow_corners' => 5, 'straights_count' => 2, 'longest_straight_m' => 700, 'lap_record_time' => '1:10.540', 'lap_record_driver' => 'Valtteri Bottas', 'lap_record_year' => 2018, 'elevation_change_m' => 43, 'type' => 'permanent', 'surface_grip' => 'medium', 'overtaking_difficulty' => 'medium'],
    'vegas' => ['length_km' => 6.201, 'laps' => 50, 'turns_count' => 17, 'fast_corners' => 7, 'medium_corners' => 5, 'slow_corners' => 5, 'straights_count' => 3, 'longest_straight_m' => 1900, 'lap_record_time' => null, 'lap_record_driver' => null, 'lap_record_year' => null, 'elevation_change_m' => 3, 'type' => 'street', 'surface_grip' => 'low', 'overtaking_difficulty' => 'medium'],
    'losail' => ['length_km' => 5.419, 'laps' => 57, 'turns_count' => 16, 'fast_corners' => 8, 'medium_corners' => 5, 'slow_corners' => 3, 'straights_count' => 2, 'longest_straight_m' => 1068, 'lap_record_time' => null, 'lap_record_driver' => null, 'lap_record_year' => null, 'elevation_change_m' => 5, 'type' => 'permanent', 'surface_grip' => 'high', 'overtaking_difficulty' => 'medium'],
    'yas_marina' => ['length_km' => 5.281, 'laps' => 58, 'turns_count' => 16, 'fast_corners' => 6, 'medium_corners' => 5, 'slow_corners' => 5, 'straights_count' => 3, 'longest_straight_m' => 1140, 'lap_record_time' => '1:26.103', 'lap_record_driver' => 'Max Verstappen', 'lap_record_year' => 2021, 'elevation_change_m' => 5, 'type' => 'permanent', 'surface_grip' => 'medium', 'overtaking_difficulty' => 'medium'],
    'shanghai' => ['length_km' => 5.451, 'laps' => 56, 'turns_count' => 16, 'fast_corners' => 6, 'medium_corners' => 5, 'slow_corners' => 5, 'straights_count' => 2, 'longest_straight_m' => 1170, 'lap_record_time' => '1:32.238', 'lap_record_driver' => 'Michael Schumacher', 'lap_record_year' => 2004, 'elevation_change_m' => 8, 'type' => 'permanent', 'surface_grip' => 'medium', 'overtaking_difficulty' => 'medium'],
    'baku' => ['length_km' => 6.003, 'laps' => 51, 'turns_count' => 20, 'fast_corners' => 6, 'medium_corners' => 6, 'slow_corners' => 8, 'straights_count' => 2, 'longest_straight_m' => 2200, 'lap_record_time' => '1:43.009', 'lap_record_driver' => 'Charles Leclerc', 'lap_record_year' => 2019, 'elevation_change_m' => 10, 'type' => 'street', 'surface_grip' => 'low', 'overtaking_difficulty' => 'low'],
    'villeneuve' => ['length_km' => 4.361, 'laps' => 70, 'turns_count' => 14, 'fast_corners' => 5, 'medium_corners' => 4, 'slow_corners' => 5, 'straights_count' => 3, 'longest_straight_m' => 1050, 'lap_record_time' => '1:13.078', 'lap_record_driver' => 'Valtteri Bottas', 'lap_record_year' => 2019, 'elevation_change_m' => 5, 'type' => 'hybrid', 'surface_grip' => 'low', 'overtaking_difficulty' => 'medium'],
    // Madring (Мадрид) — нова писта за 2026, още няма потвърдени технически данни.
    'madring' => ['length_km' => 5.474, 'laps' => null, 'turns_count' => 22, 'fast_corners' => null, 'medium_corners' => null, 'slow_corners' => null, 'straights_count' => null, 'longest_straight_m' => null, 'lap_record_time' => null, 'lap_record_driver' => null, 'lap_record_year' => null, 'elevation_change_m' => null, 'type' => 'hybrid', 'surface_grip' => null, 'overtaking_difficulty' => null],
];
